<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260822155824 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE belong (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_status VARCHAR(255) NOT NULL, member_id INT NOT NULL, tribe_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BFFF81BB7597D3FE ON belong (member_id)');
        $this->addSql('CREATE INDEX IDX_BFFF81BB6F3EE0AD ON belong (tribe_id)');
        $this->addSql('CREATE TABLE item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, image_url VARCHAR(255) DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1F1B251E7E3C61F9 ON item (owner_id)');
        $this->addSql('CREATE TABLE tribe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, code INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tribe_item (tribe_id INT NOT NULL, item_id INT NOT NULL, PRIMARY KEY (tribe_id, item_id))');
        $this->addSql('CREATE INDEX IDX_CDD57C6A6F3EE0AD ON tribe_item (tribe_id)');
        $this->addSql('CREATE INDEX IDX_CDD57C6A126F525E ON tribe_item (item_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pseudo VARCHAR(150) NOT NULL, name VARCHAR(255) NOT NULL, surname VARCHAR(255) NOT NULL, mail VARCHAR(255) NOT NULL, password VARCHAR(150) NOT NULL, role JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_item (user_id INT NOT NULL, item_id INT NOT NULL, PRIMARY KEY (user_id, item_id))');
        $this->addSql('CREATE INDEX IDX_659A69D7A76ED395 ON user_item (user_id)');
        $this->addSql('CREATE INDEX IDX_659A69D7126F525E ON user_item (item_id)');
        $this->addSql('ALTER TABLE belong ADD CONSTRAINT FK_BFFF81BB7597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE belong ADD CONSTRAINT FK_BFFF81BB6F3EE0AD FOREIGN KEY (tribe_id) REFERENCES tribe (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tribe_item ADD CONSTRAINT FK_CDD57C6A6F3EE0AD FOREIGN KEY (tribe_id) REFERENCES tribe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tribe_item ADD CONSTRAINT FK_CDD57C6A126F525E FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_item ADD CONSTRAINT FK_659A69D7A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_item ADD CONSTRAINT FK_659A69D7126F525E FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE belong DROP CONSTRAINT FK_BFFF81BB7597D3FE');
        $this->addSql('ALTER TABLE belong DROP CONSTRAINT FK_BFFF81BB6F3EE0AD');
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251E7E3C61F9');
        $this->addSql('ALTER TABLE tribe_item DROP CONSTRAINT FK_CDD57C6A6F3EE0AD');
        $this->addSql('ALTER TABLE tribe_item DROP CONSTRAINT FK_CDD57C6A126F525E');
        $this->addSql('ALTER TABLE user_item DROP CONSTRAINT FK_659A69D7A76ED395');
        $this->addSql('ALTER TABLE user_item DROP CONSTRAINT FK_659A69D7126F525E');
        $this->addSql('DROP TABLE belong');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE tribe');
        $this->addSql('DROP TABLE tribe_item');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_item');
    }
}
